// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0gxFg_4CDrpUPA23Q_05aMVcRoAsHpSE',
    appId: '1:732124150275:web:3317fd33902a1aeb4eac36',
    messagingSenderId: '732124150275',
    projectId: 'stylish-10120',
    authDomain: 'stylish-10120.firebaseapp.com',
    storageBucket: 'stylish-10120.firebasestorage.app',
    measurementId: 'G-Z7DLWKDRZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYVwKmzgSKzGwmCAK3C64kzvpF-xHt1SQ',
    appId: '1:732124150275:android:81226fbfea3d1ab64eac36',
    messagingSenderId: '732124150275',
    projectId: 'stylish-10120',
    storageBucket: 'stylish-10120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtPR35ZgZDiBk0lOyG9vwbH9V48shuQw',
    appId: '1:732124150275:ios:84dc67ad1e1e0aaf4eac36',
    messagingSenderId: '732124150275',
    projectId: 'stylish-10120',
    storageBucket: 'stylish-10120.firebasestorage.app',
    androidClientId: '732124150275-0kd39elb85al8fpu7g8g0gjag2stj0d6.apps.googleusercontent.com',
    iosClientId: '732124150275-26q1ufiaj7dv3ivqm1c5jh0h99posoku.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKtPR35ZgZDiBk0lOyG9vwbH9V48shuQw',
    appId: '1:732124150275:ios:84dc67ad1e1e0aaf4eac36',
    messagingSenderId: '732124150275',
    projectId: 'stylish-10120',
    storageBucket: 'stylish-10120.firebasestorage.app',
    androidClientId: '732124150275-0kd39elb85al8fpu7g8g0gjag2stj0d6.apps.googleusercontent.com',
    iosClientId: '732124150275-26q1ufiaj7dv3ivqm1c5jh0h99posoku.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0gxFg_4CDrpUPA23Q_05aMVcRoAsHpSE',
    appId: '1:732124150275:web:65fa2f993399efa14eac36',
    messagingSenderId: '732124150275',
    projectId: 'stylish-10120',
    authDomain: 'stylish-10120.firebaseapp.com',
    storageBucket: 'stylish-10120.firebasestorage.app',
    measurementId: 'G-12JKTXT0X2',
  );
}
